language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5.1"
#  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: 
    - "pip install -r requirements.txt"
    - "pip install ."
# command to run tests
script: nosetests
#
branches:
  only:
    - master
    - develop
